---
name: DEV FE CI
on:
  push:
    paths:
      - 'ui/**'
    branches:
      - main
  pull_request:
    paths:
      - 'ui/**'

permissions:
  contents: read
  packages: write
  checks: write
  pull-requests: write
  repository-projects: read

env:
  NODE_OPTIONS: '—-max_old_space_size=4096'

jobs:
  cache_pnpm:
    name: Cache PNPM
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: pnpm/action-setup@v2
        with:
          version: 8


      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'
          cache-dependency-path: 'ui/pnpm-lock.yaml'

      - name: Install dependencies
        run: cd ui && make init

  CI_checks:
    runs-on: ubuntu-latest
    needs: cache_pnpm
    strategy:
      matrix:
        action: ['lint', 'format', 'test', 'build']
    defaults:
      run:
        working-directory: ui
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'
          cache-dependency-path: 'ui/pnpm-lock.yaml'

      - run: make init

      - name: lint
        if: matrix.action == 'lint'
        run: make lint

      - name: format
        if: matrix.action == 'format'
        run: make format

      - name: test
        if: matrix.action == 'test'
        run: make test

      - name: build
        if: matrix.action == 'build'
        run: make build

      - name: Check for changes
        id: check_changes
        run: |
          git config --global user.email "ci-bot@percona.com"
          git config --global user.name "CI Bot"
          git diff --exit-code || echo "::set-output name=changes::true"

      - uses: stefanzweifel/git-auto-commit-action@v5
        if: steps.check_changes.outputs.changes == 'true' && github.event_name == 'pull_request'
        with:
          commit_message: 'chore: lint/format'
          token: ${{ secrets.ROBOT_TOKEN }}
